new_passage = '''
# P29: Solar Energy (Contextual Irrelevance & Topic)
{
 "id": "t_new_1", 
 "text": "(1) Solar energy is becoming an increasingly popular source of renewable energy worldwide. (2) It is generated by capturing sunlight and converting it into electricity using solar panels. (3) Many countries are investing in solar technology to reduce their dependence on fossil fuels. (4) Solar panels are most effective in areas that receive a high amount of sunlight throughout the year. (5) However, some people prefer using public transportation instead of private cars. (6) Weather conditions, such as cloudy days, can reduce the efficiency of solar energy systems. (7) Advances in technology continue to improve the performance and affordability of solar panels. (8) As a result, solar energy is expected to play a major role in the future of global energy production.",
 "questions": [
    {"subject": "English", "topic": "Paragraph Cohesion", "question_text": "The sentence which is irrelevant to the topic of paragraph is", "options": [{"letter":"A","text":"Sentence 2"}, {"letter":"B","text":"Sentence 4"}, {"letter":"C","text":"Sentence 5"}, {"letter":"D","text":"Sentence 6"}, {"letter":"E","text":"Sentence 7"}], "correct_answer": "C", "explanation": "The passage is consistently discussing the generation, usage, and efficiency of solar energy. Sentence 5 abruptly introduces 'public transportation', which lacks any context to solar energy and breaks the topic sequence."},
    {"subject": "English", "topic": "Reading Comprehension", "question_text": "What is the topic of the paragraph?", "options": [{"letter":"A","text":"The disadvantages of renewable energy"},{"letter":"B","text":"The development and use of solar energy"}, {"letter":"C","text":"The benefits of public transportation"}, {"letter":"D","text":"The causes of climate change"}, {"letter":"E","text":"The history of fossil fuels"}], "correct_answer": "B", "explanation": "The main focus across the sentences (ignoring the irrelevant one) is how solar energy is popular, generated, invested in, affected by weather, and expected to grow—pointing directly to its development and use."}
 ]
}
'''

with open('c:\\Users\\Axioo Pongo\\OneDrive\\Desktop\\SIMAK\\practice\\english_pool_v4.py', 'r', encoding='utf-8') as f:
    text = f.read()

# Replace the closing bracket ']' with the new passage and ']'
if text.strip().endswith(']'):
    text = text[:text.rfind(']')] + ",\n" + new_passage + "\n]"
    with open('c:\\Users\\Axioo Pongo\\OneDrive\\Desktop\\SIMAK\\practice\\english_pool_v4.py', 'w', encoding='utf-8') as f:
        f.write(text)
    print("Injected successfully.")
else:
    print("Could not find terminating bracket.")
