import json

numbered_passages = [
{
 "id": "t1_numbered", 
 "text": "(1) Solar energy is becoming an increasingly popular source of renewable energy worldwide. (2) It is generated by capturing sunlight and converting it into electricity using solar panels. (3) Many countries are investing in solar technology to reduce their dependence on fossil fuels. (4) Solar panels are most effective in areas that receive a high amount of sunlight throughout the year. (5) However, some people prefer using public transportation instead of private cars. (6) Weather conditions, such as cloudy days, can reduce the efficiency of solar energy systems. (7) Advances in technology continue to improve the performance and affordability of solar panels. (8) As a result, solar energy is expected to play a major role in the future of global energy production.",
 "questions": [
    {"subject": "English", "topic": "Paragraph Cohesion", "question_text": "The sentence which is irrelevant to the topic of paragraph is", "options": [{"letter":"A","text":"Sentence 2"}, {"letter":"B","text":"Sentence 4"}, {"letter":"C","text":"Sentence 5"}, {"letter":"D","text":"Sentence 6"}, {"letter":"E","text":"Sentence 7"}], "correct_answer": "C", "explanation": "The passage consistently discusses the generation, usage, and efficiency of solar energy. Sentence 5 abruptly introduces 'public transportation', which lacks context to solar energy and breaks the topic sequence."},
    {"subject": "English", "topic": "Reading Comprehension", "question_text": "What is the topic of the paragraph?", "options": [{"letter":"A","text":"The disadvantages of renewable energy"},{"letter":"B","text":"The development and use of solar energy"}, {"letter":"C","text":"The benefits of public transportation"}, {"letter":"D","text":"The causes of climate change"}, {"letter":"E","text":"The history of fossil fuels"}], "correct_answer": "B", "explanation": "The main focus across the sentences (excluding the irrelevant one) is how solar energy is generated, invested in, affected by weather, and expected to grow—pointing directly to its development and use."}
 ]
},
{
 "id": "t2_numbered", 
 "text": "(1) Deep-sea exploration has revealed entirely new ecosystems that thrive in extreme darkness and pressure. (2) Specialized submarines and remote-operated vehicles are used to navigate these hostile environments. (3) Researchers have discovered bizarre creatures like the anglerfish and giant tube worms. (4) These organisms rely on hydrothermal vents rather than sunlight for their energy. (5) Climbing tall mountains requires specialized climbing gear and oxygen tanks. (6) The data collected from the ocean floor helps scientists understand the origins of life on Earth. (7) Despite these advances, the majority of the deep ocean remains unmapped and unexplored. (8) Future missions aim to uncover even more secrets hidden within these massive underwater trenches.",
 "questions": [
    {"subject": "English", "topic": "Paragraph Cohesion", "question_text": "The sentence which is irrelevant to the topic of paragraph is", "options": [{"letter":"A","text":"Sentence 3"}, {"letter":"B","text":"Sentence 4"}, {"letter":"C","text":"Sentence 5"}, {"letter":"D","text":"Sentence 6"}, {"letter":"E","text":"Sentence 7"}], "correct_answer": "C", "explanation": "The paragraph is focused on deep-sea exploration, marine life, and underwater ecosystems. Sentence 5 discusses 'climbing tall mountains', which is completely unrelated to the deep-sea topic."},
    {"subject": "English", "topic": "Reading Comprehension", "question_text": "What is the topic of the paragraph?", "options": [{"letter":"A","text":"The dangers of climbing mountains"},{"letter":"B","text":"The biological organisms relying on solar energy"}, {"letter":"C","text":"The ongoing exploration and discoveries of the deep ocean"}, {"letter":"D","text":"The history of submarine warfare"}, {"letter":"E","text":"The mapping of global trade routes"}], "correct_answer": "C", "explanation": "Except for the outlier sentence, every line details the mechanisms, discoveries, and future goals of exploring the deep-sea ecosystem."}
 ]
},
{
 "id": "t3_numbered", 
 "text": "(1) Vertical farming is an innovative agricultural practice designed to maximize crop yield in limited urban spaces. (2) Instead of sprawling fields, crops are grown in stacked layers within climate-controlled buildings. (3) This method significantly reduces the agricultural reliance on massive amounts of land and fresh water. (4) Advanced LED lighting systems provide the exact spectrum of light required for photosynthesis. (5) Fast food chains are increasingly offering plant-based meat alternatives on their menus. (6) By eliminating the need for pesticides, vertical farms produce cleaner and healthier vegetables. (7) These facilities can operate year-round regardless of external weather complications. (8) Ultimately, vertical farming could be the key to ensuring food security for rapidly expanding city populations.",
 "questions": [
    {"subject": "English", "topic": "Paragraph Cohesion", "question_text": "The sentence which is irrelevant to the topic of paragraph is", "options": [{"letter":"A","text":"Sentence 3"}, {"letter":"B","text":"Sentence 4"}, {"letter":"C","text":"Sentence 5"}, {"letter":"D","text":"Sentence 6"}, {"letter":"E","text":"Sentence 8"}], "correct_answer": "C", "explanation": "The passage details the mechanics, benefits, and future of vertical farming. Sentence 5 randomly mentions 'fast food chains offering plant-based meat', which strays entirely from the agricultural methodology of vertical farming."},
    {"subject": "English", "topic": "Reading Comprehension", "question_text": "What is the topic of the paragraph?", "options": [{"letter":"A","text":"The techniques and benefits of vertical farming"},{"letter":"B","text":"The health benefits of plant-based meats"}, {"letter":"C","text":"The manufacturing process of LED lights"}, {"letter":"D","text":"The rise of fast food consumption in urban areas"}, {"letter":"E","text":"The history of traditional agriculture"}], "correct_answer": "A", "explanation": "Every relevant sentence highlights how vertical farming works (layered floors, LEDs) or its advantages (saving water, pesticide-free, year-round operation)."}
 ]
},
{
 "id": "t4_numbered", 
 "text": "(1) Electronic sports, commonly known as e-sports, have transformed competitive gaming into a multi-billion-dollar global industry. (2) Professional players train for hours daily to master complex strategies and lightning-fast reflexes. (3) Major tournaments are broadcasted to millions of viewers online and often fill massive sports arenas. (4) Many top players are sponsored by major brands and earn substantial incomes through prize money. (5) Traditional board games like chess and checkers have been played for centuries. (6) Universities have even started offering scholarships to recruit talented gamers for their collegiate teams. (7) The rapid growth of the industry has led to the establishment of dedicated regulatory bodies. (8) As technology advances, the boundary between physical sports and competitive gaming continues to blur.",
 "questions": [
    {"subject": "English", "topic": "Paragraph Cohesion", "question_text": "The sentence which is irrelevant to the topic of paragraph is", "options": [{"letter":"A","text":"Sentence 3"}, {"letter":"B","text":"Sentence 4"}, {"letter":"C","text":"Sentence 5"}, {"letter":"D","text":"Sentence 6"}, {"letter":"E","text":"Sentence 7"}], "correct_answer": "C", "explanation": "The passage is devoted strictly to the modern phenomenon of electronic sports (e-sports) and its massive industry. Sentence 5 discusses 'traditional board games', which disrupts the coherent flow regarding digital professional gaming."},
    {"subject": "English", "topic": "Reading Comprehension", "question_text": "What is the topic of the paragraph?", "options": [{"letter":"A","text":"The historical strategies of chess"},{"letter":"B","text":"The decline of traditional university sports"}, {"letter":"C","text":"The professionalization and massive scale of e-sports"}, {"letter":"D","text":"The technological manufacturing of gaming computers"}, {"letter":"E","text":"The dangers of video game addiction"}], "correct_answer": "C", "explanation": "The paragraph consistently outlines how e-sports has become a legitimate, highly lucrative, and massively viewed professional industry."}
 ]
}
]

with open('c:\\Users\\Axioo Pongo\\OneDrive\\Desktop\\SIMAK\\practice\\english_pool_v4.py', 'r', encoding='utf-8') as f:
    text = f.read()

# Remove the previously appended Solar Energy passage
if '# P29: Solar Energy' in text:
    text = text[:text.find('# P29: Solar Energy')].strip()
    if text.endswith(','): text = text[:-1].strip()

# Now the text should end with `]}` or just `]`
# We want to replace the final `]` with `, <our newly formatted 4 passages>, ]`
if text.endswith(']'):
    text = text[:-1].strip()
    if not text.endswith(','):
        text += ','
        
    passages_str = json.dumps(numbered_passages, indent=2)
    # The JSON string represents a list, so we strip the outer [ and ]
    passages_str = passages_str[1:-1]
    
    text += passages_str + '\n]'
    
    with open('c:\\Users\\Axioo Pongo\\OneDrive\\Desktop\\SIMAK\\practice\\english_pool_v4.py', 'w', encoding='utf-8') as f:
        f.write(text)
    print("Injected 4 structured passages successfully.")
else:
    print("Could not find terminating bracket.")
